# -*- coding: utf-8 -*-
"""
/***************************************************************************
 baseMapLoader
                                 A QGIS plugin
 Loads pre-configured base map QLR into SWICT corporate projects dynamically on load
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-09
        copyright            : (C) 2024 by Simon Warren  (SWICT)
        email                : simon.warren@wychavon.gov.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load baseMapLoader class from file baseMapLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .base_map_loader import baseMapLoader
    return baseMapLoader(iface)
